services:
  catalogdb:
    image: mongo
    
  microservice.catalog.api:
    image: microservice.catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/MicroService.Catalog.API/Dockerfile
      
volumes:
  mongo_data: